name: Deploy Hugo to Server

on:
  push:
    branches:
      - main  # 监听 main 分支的推送

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive  # 极其重要：必须拉取 PaperMod 主题

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.146.0' # 匹配你本地的版本
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-hugo-deploy@v2
        with:
          publish_dir: ./public
          # 这里会自动创建一个叫 gh-pages 的分支来存放网页