name: Deploy Hugo to Server

on:
  push:
    branches:
      - main  # 监听 main 分支的推送

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive  # 极其重要：必须拉取 PaperMod 主题

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.159.0' # hugo-theme-stack 需要 >= 0.157.0
          extended: true

      - name: Build
        run: hugo --minify --quiet

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4  # 修正了仓库名，并使用了最新的 v4 版本
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # 这是一个内置变量，不需要你手动去 Secrets 填
          publish_dir: ./public